import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Document } from './document';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const documents = [
        { documentId: 1, name: 'Toxicity report 1', text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 2, name: 'Toxicity report 2' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 3, name: 'Toxicity report 3' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 4, name: 'Toxicity report 4' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 5, name: 'Toxicity report 5' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 6, name: 'Toxicity report 6' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 7, name: 'Toxicity report 7' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 8, name: 'Toxicity report 8' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 9, name: 'Toxicity report 9' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' },
        { documentId: 10, name: 'Toxicity report 10' , text:'The relative and absolute testes weights were lower than in control animals, but a dose- relationship could not be detected. The testes showed an arrested spermatogenesis with loss of round spermatids or tubular atrophy. The seminal vesicles showed reduced secretion. - Signs of increased atresia of tertiary follicles in the ovary and hyperplasia of secretory cells in the oviducts were observed. These changes were not closely dose-related, however, this may be due to the onset of treatment in different cycle stages. The relative uterus weight was higher than those in control animals; however, a dose-relationship could not be detected. - Lobular hyperplasia of the mammary gland was found in male and female animals, whereby the severity of hyperplasia (up to moderate) and the number of affected animals increased with ascending doses.' }
      ];
    return {documents};
  }

  // Overrides the genId method to ensure that a hero always has an id.
  // If the heroes array is empty,
  // the method below returns the initial number (11).
  // if the heroes array is not empty, the method below returns the highest
  // hero id + 1.
  genId(documents: Document[]): number {
    return documents.length > 0 ? Math.max(...documents.map(document => document.documentId)) + 1 : 11;
  }
}
